name: Generate contribution snake

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: sharonjoseph12
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-contribution-grid-snake-dark.gif?palette=github-dark&color_snake=4DE2FF&color_background=0B0F17
            dist/github-contribution-grid-snake.gif?palette=github-light

      - name: Publish generated assets
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
